# Notebook 1 – Dataset Understanding

## 1. What is a Dataset?
**Definition:** A dataset is an organized collection of related observations, usually arranged in rows and columns. Each row represents an observation and each column records one property.

**Simple example:** A table of three students with name, age, and marks is a dataset.

**Real-world example:** A hospital may keep a dataset of patient visits, symptoms, tests, and outcomes.

**Business example:** A shop stores product name, price, quantity sold, and sale date to understand performance.

**AI/ML use case:** A model learns patterns from historical examples in a dataset to predict an outcome for new cases.

**Why it matters:** If the dataset is incomplete, biased, or does not match the problem, analysis and predictions can be misleading.

## 2. Create and load the dataset

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

df = pd.DataFrame({
    "employee_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012],
    "age": [22, 25, 29, 31, 35, 41, 27, 38, 45, 24, np.nan, 31],
    "department": ["IT", "HR", "IT", "Sales", "IT", "Finance", "Sales", "HR", "Finance", "IT", "Sales", "it "],
    "education": ["Bachelor", "Master", "Bachelor", "Bachelor", "Master", "PhD", "Bachelor", "Master", "Bachelor", "Bachelor", "Master", "Bachelor"],
    "monthly_salary": [28000, 35000, 45000, 42000, 65000, 82000, 39000, 56000, 90000, 32000, 47000, 45000],
    "monthly_spending": [12000, 16000, 20000, 19000, 25000, 30000, 18000, 24000, 32000, 15000, 21000, 20000],
    "remote": ["No", "Yes", "Yes", "No", "Yes", "Yes", "No", "Yes", "No", "No", "Yes", "Yes"],
    "joined_date": pd.to_datetime(["2022-01-10", "2021-05-15", "2020-03-01", "2023-02-20", "2018-07-12", "2016-11-30", "2022-09-05", "2019-04-18", "2014-08-25", "2023-06-01", "2020-12-14", "2021-08-09"]),
    "left_company": ["No", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No", "Yes", "No"]
})
df

,employee_id,age,department,education,monthly_salary,monthly_spending,remote,joined_date,left_company
0,1001,22.0,IT,Bachelor,28000,12000,No,2022-01-10,No
1,1002,25.0,HR,Master,35000,16000,Yes,2021-05-15,No
2,1003,29.0,IT,Bachelor,45000,20000,Yes,2020-03-01,No
3,1004,31.0,Sales,Bachelor,42000,19000,No,2023-02-20,Yes
4,1005,35.0,IT,Master,65000,25000,Yes,2018-07-12,No
5,1006,41.0,Finance,PhD,82000,30000,Yes,2016-11-30,No
6,1007,27.0,Sales,Bachelor,39000,18000,No,2022-09-05,Yes
7,1008,38.0,HR,Master,56000,24000,Yes,2019-04-18,No
8,1009,45.0,Finance,Bachelor,90000,32000,No,2014-08-25,No
9,1010,24.0,IT,Bachelor,32000,15000,No,2023-06-01,No
10,1011,NaN,Sales,Master,47000,21000,Yes,2020-12-14,Yes
11,1012,31.0,it,Bachelor,45000,20000,Yes,2021-08-09,No

## 3. What is a Feature?
**Definition:** A feature is an input variable that describes an observation. It is usually represented by a column.

**Simple example:** In a student dataset, study hours and attendance can be features.

**Real-world example:** In a house dataset, location, size, and number of bedrooms are features.

**Business example:** For sales forecasting, price, promotion, and day of week can be features.

**AI/ML use case:** Features such as age and monthly salary may help a model estimate whether an employee might leave.

**Why it matters:** Relevant features help models learn useful patterns; irrelevant or leaked features can harm performance.

## 4. What is a Target?
**Definition:** The target is the outcome a supervised machine-learning model is trained to predict.

**Simple example:** If predicting exam results, the target could be pass/fail.

**Real-world example:** A weather model may predict tomorrow's temperature.

**Business example:** A retailer may predict next month's sales.

**AI/ML use case:** `left_company` is a possible target for predicting employee attrition.

**Why it matters:** A clearly defined target determines what the model learns and how success is measured.

## 5. Independent and Dependent Variables
**Definition:** Independent variables are inputs or predictors; the dependent variable is the outcome being studied or predicted. In ML, these often correspond to features (X) and target (y).

**Simple example:** Study hours (independent) may help explain exam score (dependent).

**Real-world example:** Exercise duration may be studied in relation to heart rate, while remembering that other factors also matter.

**Business example:** Advertising spend may be compared with sales revenue.

**AI/ML use case:** Salary, department, and age can be inputs (X); employee departure can be the target (y).

**Why it matters:** Separating inputs and outcome prevents accidentally training on the answer itself. Association does not prove causation.

In [ ]:
target_column = "left_company"
identifier_columns = ["employee_id"]
feature_columns = [c for c in df.columns if c not in identifier_columns + [target_column]]
X = df[feature_columns]
y = df[target_column]
print("Feature matrix X shape:", X.shape)
print("Target y shape:", y.shape)
display(X.head())
display(y.head())

## 6. Numerical Features
**Definition:** Numerical features are values represented by numbers where arithmetic may be meaningful, such as salary or spending.

**Simple example:** Marks of 70, 85, and 90.

**Real-world example:** Temperature readings from sensors.

**Business example:** Revenue, cost, order quantity, and salary.

**AI/ML use case:** Models use numerical features directly or after scaling/transformations.

**Why it matters:** Numerical columns can be summarized with mean, median, spread, and plots; their units and outliers should be checked.

## 7. Categorical Features
**Definition:** Categorical features represent groups or labels, such as department or education level.

**Simple example:** Red, blue, and green are categories.

**Real-world example:** A patient's blood group is categorical.

**Business example:** Product category, payment method, or region.

**AI/ML use case:** A model may encode department or education using one-hot or ordinal encoding, depending on meaning.

**Why it matters:** Categories must be consistent; `IT`, `it`, and `IT ` may otherwise be treated as different values.

## 8. Discrete Features
**Definition:** Discrete values are countable, often whole-number counts.

**Simple example:** Number of books: 0, 1, 2, 3.

**Real-world example:** Number of visits to a clinic.

**Business example:** Units sold per order.

**AI/ML use case:** Number of previous complaints may help predict customer churn.

**Why it matters:** Discrete variables often have a limited set of possible values and may need count-aware summaries or models.

## 9. Continuous Features
**Definition:** Continuous variables can take any value within a range in principle, including fractional values.

**Simple example:** A person's height may be 170.5 cm.

**Real-world example:** Time taken to travel or sensor temperature.

**Business example:** Delivery time in hours or product weight.

**AI/ML use case:** Continuous measurements may be inputs to regression models.

**Why it matters:** Histograms, distributions, outliers, units, and scaling can affect how these features are analyzed and modeled.

## 10. Identifier Columns
**Definition:** An identifier uniquely labels a record, such as employee ID or order number. It usually names the record rather than measuring a meaningful quantity.

**Simple example:** Student ID 1024.

**Real-world example:** A tracking number for a parcel.

**Business example:** Invoice number.

**AI/ML use case:** Usually remove IDs from model inputs unless the ID carries a justified signal. IDs can encourage memorization or data leakage.

**Why it matters:** Numeric IDs should not automatically be analyzed as quantities or treated as meaningful numeric features.

## 11. Target Variable
**Definition:** The target variable is the specific dependent variable selected for the modeling objective. It can be numeric (regression) or categorical (classification).

**Simple example:** Predicting a student's final mark uses the mark as a numeric target.

**Real-world example:** Predicting whether a machine will fail uses failure status as a categorical target.

**Business example:** Predicting whether a customer will renew a subscription.

**AI/ML use case:** `left_company` can be the target for employee attrition classification.

**Why it matters:** Target labels must be accurate, available at the correct time, and consistent with the business question.

## 12. Metadata
**Definition:** Metadata is information describing the dataset, its source, structure, collection process, units, and limitations.

**Simple example:** “Marks are out of 100; collected in June.”

**Real-world example:** Sensor brand, measurement units, and collection time.

**Business example:** Sales data source, currency, region coverage, and reporting period.

**AI/ML use case:** Metadata helps assess whether training data matches production data and whether the dataset has known limitations.

**Why it matters:** Without metadata, analysts may misunderstand units, time coverage, or how values were collected.

## 13. Dataset Dimensions
**Definition:** Dataset dimensions describe the number of rows and columns, commonly shown as `(rows, columns)` in Pandas.

**Simple example:** 10 students and 4 fields gives 10 rows and 4 columns.

**Real-world example:** 1 million sensor readings and 12 fields.

**Business example:** Number of transactions and transaction attributes in a sales table.

**AI/ML use case:** Dimensions help estimate memory needs and understand the amount of training data.

**Why it matters:** Very small datasets may not generalize well; very wide datasets can need feature selection or memory optimization.

In [4]:
print("Dataset dimensions (rows, columns):", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Column names:", df.columns.tolist())
display(df.head())

Dataset dimensions (rows, columns): (12, 9)
Rows: 12
Columns: 9
Column names: ['employee_id', 'age', 'department', 'education', 'monthly_salary', 'monthly_spending', 'remote', 'joined_date', 'left_company']

,employee_id,age,department,education,monthly_salary,monthly_spending,remote,joined_date,left_company
0,1001,22.0,IT,Bachelor,28000,12000,No,2022-01-10,No
1,1002,25.0,HR,Master,35000,16000,Yes,2021-05-15,No
2,1003,29.0,IT,Bachelor,45000,20000,Yes,2020-03-01,No
3,1004,31.0,Sales,Bachelor,42000,19000,No,2023-02-20,Yes
4,1005,35.0,IT,Master,65000,25000,Yes,2018-07-12,No

## 14. Document this dataset
- **Dataset name:** Fictional employee sample
- **Unit of observation:** One employee record
- **Possible target:** `left_company`
- **Identifier:** `employee_id`
- **Numerical columns:** age, monthly_salary, monthly_spending (employee_id is numeric-looking but is an identifier)
- **Categorical columns:** department, education, remote, left_company
- **Date/time column:** joined_date
- **Known quality issues:** missing age and inconsistent department text

**ML impact:** This understanding guides cleaning, encoding, feature selection, and target definition before training.